In [10]:
import pandas as pd
from helper import sort_cluster_by_feature, lookup_table, compare_clusters , percentage_null_data_in_cluster,save_dataframe, print_oldest_dates

In [8]:
import ee
from config import PROJECT_ID

try:
    ee.Initialize(project=PROJECT_ID)
except Exception as e:
    print("Error initializing Earth Engine:", e)

In [2]:
df = pd.read_csv("data/Gemstat_Data_Cleaned_Raw/All_lakes_clustered_haversine.csv")

In [3]:
sort_cluster_by_feature(df , feature = "TURB" , top_n=7)

Cluster
678    2378
626     256
393     195
455     175
616     163
539     153
661     144
dtype: int64

In [4]:
lookup_table(df , cluster = 678)

,Latitude,Longitude,Region,Date,Station Identifier
38597,-34.829733,-55.042069,South America,2015-01-02,Toma de agua
38598,-34.829733,-55.042069,South America,2015-01-05,Toma de agua
38599,-34.829733,-55.042069,South America,2015-01-07,Toma de agua
38600,-34.829733,-55.042069,South America,2015-01-08,Toma de agua
38601,-34.829733,-55.042069,South America,2015-01-09,Toma de agua
...,...,...,...,...,...
41008,-34.775918,-55.064822,South America,2023-02-25,Laguna Arroyo del Sauce
41009,-34.775918,-55.064822,South America,2023-03-04,Laguna Arroyo del Sauce
41010,-34.775918,-55.064822,South America,2023-03-15,Laguna Arroyo del Sauce
41011,-34.775918,-55.064822,South America,2023-03-24,Laguna Arroyo del Sauce
41012,-34.775918,-55.064822,South America,2023-03-29,Laguna Arroyo del Sauce

In [5]:
compare_clusters(df , clusters_to_keep = [678 , 94 , 168 , 164 , 215]
    )

Cluster                    94          164         168         215         678
Station               0.000000    0.000000    0.000000    0.000000    0.000000
Date                  0.000000    0.000000    0.000000    0.000000    0.000000
Alk-Tot             100.000000  100.000000  100.000000  100.000000   26.158940
Cl-Tot               99.825480    0.000000    0.000000    0.000000  100.000000
EC                  100.000000  100.000000  100.000000  100.000000    2.069536
NH4N                  0.698080    0.000000    0.000000    4.043127  100.000000
NO2N                  0.785340    4.330176    9.009813    5.795148  100.000000
NO3N                  1.047120   39.377537   18.644068    0.000000  100.000000
O2-Dis               18.586387    6.630582   50.669045   17.654987  100.000000
TEMP                100.000000  100.000000  100.000000  100.000000    0.041391
TURB                100.000000  100.000000  100.000000  100.000000    1.572848
pH                  100.000000  100.000000  100.000000  100.000000    0.000000
Station Identifier    0.000000    0.000000    0.000000    0.000000    0.000000
Latitude              0.000000    0.000000    0.000000    0.000000    0.000000
Longitude             0.000000    0.000000    0.000000    0.000000    0.000000
Region                0.000000    0.000000    0.000000    0.000000    0.000000
TP                    0.000000    0.000000    0.267618    0.000000  100.000000
O2-Dis-Sat            0.261780    6.630582    9.455843   17.654987  100.000000
TIP                   0.087260   11.366712   44.246209   11.455526  100.000000
COL-True            100.000000  100.000000  100.000000  100.000000   12.500000
Cluster               0.000000    0.000000    0.000000    0.000000    0.000000

In [6]:
percentage_null_data_in_cluster(df , cluster=94)

Station                 0.000000
Date                    0.000000
Time                  100.000000
Alk-Tot               100.000000
Chl-a                 100.000000
Cl-Tot                 99.825480
DRP                   100.000000
EC                    100.000000
H-T                   100.000000
NH4N                    0.698080
NO2N                    0.785340
NO3N                    1.047120
O2-Dis                 18.586387
SiO2-Dis              100.000000
TDS                   100.000000
TEMP                  100.000000
TURB                  100.000000
pH                    100.000000
Station Identifier      0.000000
Latitude                0.000000
Longitude               0.000000
Region                  0.000000
Cl-Dis                100.000000
NH3N                  100.000000
SiO2-Rea              100.000000
TDP                   100.000000
TN                    100.000000
TP                      0.000000
TRANS                 100.000000
TSS                   100.000000
O2-Dis-Sat              0.261780
TIP                     0.087260
BOD                   100.000000
TOTCOLI               100.000000
A340                  100.000000
As-Tot                100.000000
COL-True              100.000000
Cd-Tot                100.000000
Cr-Tot                100.000000
DOC                   100.000000
ENTCOCC               100.000000
FECALCOLI             100.000000
Hg-Tot                100.000000
Ni-Tot                100.000000
Pb-Tot                100.000000
TEMP-Air              100.000000
TKN                   100.000000
TOC                   100.000000
TON                   100.000000
TRP                   100.000000
Ca-Dis                100.000000
Fe-Dis                100.000000
Mg-Dis                100.000000
Na-Dis                100.000000
Pb-Dis                100.000000
SO4-Dis               100.000000
Zn-Dis                100.000000
Cluster                 0.000000
dtype: float64

In [ ]:

AOI = ee.Geometry.Polygon(
    [
        [
            [-101.76803917729596, 19.40622630237513],
            [-101.53663964116315, 19.40622630237513],
            [-101.53663964116315, 19.692874430019145],
            [-101.76803917729596, 19.692874430019145],
            [-101.76803917729596, 19.40622630237513],  
        ]
    ]
)

print_oldest_dates(AOI)

Image 1:
  Date: 2018-12-16 17:28:25
  Cloud Coverage: 21.196333%

Image 2:
  Date: 2018-12-16 17:28:27
  Cloud Coverage: 17.790047%

Image 3:
  Date: 2018-12-21 17:28:23
  Cloud Coverage: 0.103311%

Image 4:
  Date: 2018-12-21 17:28:24
  Cloud Coverage: 0.116801%

Image 5:
  Date: 2018-12-26 17:28:27
  Cloud Coverage: 14.303304%

Image 6:
  Date: 2018-12-26 17:28:29
  Cloud Coverage: 21.493149%

Image 7:
  Date: 2018-12-31 17:28:25
  Cloud Coverage: 67.383924%

Image 8:
  Date: 2018-12-31 17:28:26
  Cloud Coverage: 54.719695%

Image 9:
  Date: 2019-01-05 17:28:29
  Cloud Coverage: 19.898208%

Image 10:
  Date: 2019-01-05 17:28:31
  Cloud Coverage: 5.601502%

In [7]:
df_678 = df[df['Cluster']==678]

In [ ]:
filtered_df = df_678[df_678["Date"] > "2018-05-31"]

In [ ]:
save_dataframe(df_678, save_path="data/temp" , file_name="temp_file")