In [1]:
import pandas as pd

In [40]:
df = pd.read_csv('data/Gemstat_Data_Cleaned_Raw/All_lakes_clustered_haversine.csv')

In [41]:
df

,Station,Date,Time,Alk-Tot,Chl-a,Cl-Tot,DRP,EC,H-T,NH4N,...,TON,TRP,Ca-Dis,Fe-Dis,Mg-Dis,Na-Dis,Pb-Dis,SO4-Dis,Zn-Dis,Cluster
0,TZA00011,2016-01-13,NaN,50.000000,29.682000,3.615000,45.000000,149.750000,24.500000,58.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,TZA00013,2016-01-10,NaN,44.000000,0.019800,NaN,NaN,95.000000,36.000000,0.050000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,TZA00014,2016-01-10,NaN,56.666667,24.573333,3.696667,20.000000,115.000000,34.666667,30.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,TZA00015,2016-01-07,NaN,60.000000,0.006800,NaN,NaN,111.000000,26.000000,0.050000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
4,TZA00017,2016-01-01,NaN,74.666667,32.333333,3.533333,56.666667,142.666667,31.333333,0.246667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41008,URY00175,2023-02-25,NaN,NaN,NaN,NaN,NaN,201.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,678
41009,URY00175,2023-03-04,NaN,NaN,NaN,NaN,NaN,206.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,678
41010,URY00175,2023-03-15,NaN,NaN,NaN,NaN,NaN,212.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,678
41011,URY00175,2023-03-24,NaN,NaN,NaN,NaN,NaN,188.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,678
41012,URY00175,2023-03-29,NaN,NaN,NaN,NaN,NaN,187.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,678

In [42]:
# Filter the dataframe for non-null values of the feature 'Chl-a'
filtered_df = df[df['DOC'].notnull()]

# Group by 'Cluster' and count the number of rows in each cluster
cluster_counts = filtered_df.groupby('Cluster').size()

# Sort the counts in descending order and select the top 5 clusters
top_5_clusters = cluster_counts.sort_values(ascending=False).head(15)

In [43]:
top_5_clusters

Cluster
626    255
393    194
455    175
616    163
539    153
661    142
516    124
657    124
436     96
618     94
545     93
503     85
514     80
644     79
608     79
dtype: int64

In [35]:
df[df['Cluster'] == 644][['Latitude','Longitude']]

       Latitude   Longitude
37549  26.98749 -113.166100
37550  26.98749 -113.166100
37551  26.98749 -113.166100
37552  26.98749 -113.166100
37553  26.98749 -113.166100
...         ...         ...
37623  26.87106 -113.171357
37624  26.87106 -113.171357
37625  26.87106 -113.171357
37626  26.87106 -113.171357
37627  26.87106 -113.171357

[79 rows x 2 columns]

In [37]:
df = pd.read_csv('data/Gemstat_Data_Cleaned_Raw/Europe/cleaned_samples.csv')
df.columns

Index(['Station', 'Date', 'Time', 'Cl-Tot', 'NH4N', 'NO2N', 'NO3N', 'O2-Dis',
       'O2-Dis-Sat', 'TIP', 'TP', 'Station Identifier', 'Latitude',
       'Longitude'],
      dtype='object')

In [77]:
df = pd.read_csv('data/Gemstat_Data_Cleaned_Raw/All_lakes_merged.csv')
df = df[pd.to_datetime(df['Date']).dt.year >= 2018]
df = df.drop_duplicates(subset=['Station', 'Date'])
df

,Station,Date,Time,Alk-Tot,Chl-a,Cl-Tot,DRP,EC,H-T,NH4N,...,TOC,TON,TRP,Ca-Dis,Fe-Dis,Mg-Dis,Na-Dis,Pb-Dis,SO4-Dis,Zn-Dis
26,JPN00016,2018-09-03,NaN,NaN,NaN,NaN,NaN,148.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,JPN00016,2018-09-06,NaN,NaN,NaN,NaN,NaN,128.8,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,JPN00016,2019-09-02,NaN,NaN,NaN,NaN,NaN,128.9,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,JPN00016,2020-08-25,NaN,NaN,NaN,NaN,NaN,130.3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,JPN00016,2021-08-03,NaN,NaN,NaN,NaN,NaN,131.4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41008,URY00175,2023-02-25,NaN,NaN,NaN,NaN,NaN,201.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41009,URY00175,2023-03-04,NaN,NaN,NaN,NaN,NaN,206.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41010,URY00175,2023-03-15,NaN,NaN,NaN,NaN,NaN,212.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41011,URY00175,2023-03-24,NaN,NaN,NaN,NaN,NaN,188.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41012,URY00175,2023-03-29,NaN,NaN,NaN,NaN,NaN,187.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
df.columns

Index(['Station', 'Date', 'Time', 'Alk-Tot', 'Chl-a', 'Cl-Tot', 'DRP', 'EC',
       'H-T', 'NH4N', 'NO2N', 'NO3N', 'O2-Dis', 'SiO2-Dis', 'TDS', 'TEMP',
       'TURB', 'pH', 'Station Identifier', 'Latitude', 'Longitude', 'Region',
       'Cl-Dis', 'NH3N', 'SiO2-Rea', 'TDP', 'TN', 'TP', 'TRANS', 'TSS',
       'O2-Dis-Sat', 'TIP', 'BOD', 'TOTCOLI', 'A340', 'As-Tot', 'COL-True',
       'Cd-Tot', 'Cr-Tot', 'DOC', 'ENTCOCC', 'FECALCOLI', 'Hg-Tot', 'Ni-Tot',
       'Pb-Tot', 'TEMP-Air', 'TKN', 'TOC', 'TON', 'TRP', 'Ca-Dis', 'Fe-Dis',
       'Mg-Dis', 'Na-Dis', 'Pb-Dis', 'SO4-Dis', 'Zn-Dis'],
      dtype='object')

In [98]:
FECALCOLI_Data = df[df['TURB'].notnull()]
FECALCOLI_Data

,Station,Date,Time,Alk-Tot,Chl-a,Cl-Tot,DRP,EC,H-T,NH4N,...,TOC,TON,TRP,Ca-Dis,Fe-Dis,Mg-Dis,Na-Dis,Pb-Dis,SO4-Dis,Zn-Dis
29907,MEX00157,2018-01-19,NaN,NaN,0.0073,NaN,NaN,655.7,NaN,NaN,...,4.843,1.4526,0.0010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29908,MEX00157,2018-07-23,NaN,NaN,0.0020,NaN,NaN,643.7,NaN,NaN,...,7.112,3.4179,0.0088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29909,MEX00157,2018-10-23,NaN,NaN,0.0055,NaN,NaN,671.0,NaN,NaN,...,4.566,1.2715,0.0010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29910,MEX00157,2019-02-05,NaN,NaN,0.0076,NaN,NaN,839.0,NaN,NaN,...,10.991,2.1318,0.0178,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29911,MEX00157,2020-07-27,NaN,NaN,NaN,NaN,NaN,538.0,NaN,NaN,...,5.502,1.1247,0.0070,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41008,URY00175,2023-02-25,NaN,NaN,NaN,NaN,NaN,201.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41009,URY00175,2023-03-04,NaN,NaN,NaN,NaN,NaN,206.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41010,URY00175,2023-03-15,NaN,NaN,NaN,NaN,NaN,212.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41011,URY00175,2023-03-24,NaN,NaN,NaN,NaN,NaN,188.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41012,URY00175,2023-03-29,NaN,NaN,NaN,NaN,NaN,187.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
FECALCOLI_Data.Station.value_counts()

Station
URY00076    1073
URY00174      93
URY00175      92
URY00080      92
URY00078      92
            ...
MEX05355       1
MEX05693       1
MEX05532       1
MEX05635       1
MEX03178       1
Name: count, Length: 620, dtype: int64

In [100]:
#Columns Starting with MEX
FECALCOLI_Data[FECALCOLI_Data['Station'].str.startswith('MEX')]

,Station,Date,Time,Alk-Tot,Chl-a,Cl-Tot,DRP,EC,H-T,NH4N,...,TOC,TON,TRP,Ca-Dis,Fe-Dis,Mg-Dis,Na-Dis,Pb-Dis,SO4-Dis,Zn-Dis
29907,MEX00157,2018-01-19,NaN,NaN,0.007300,NaN,NaN,655.7,NaN,NaN,...,4.843,1.45260,0.0010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29908,MEX00157,2018-07-23,NaN,NaN,0.002000,NaN,NaN,643.7,NaN,NaN,...,7.112,3.41790,0.0088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29909,MEX00157,2018-10-23,NaN,NaN,0.005500,NaN,NaN,671.0,NaN,NaN,...,4.566,1.27150,0.0010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29910,MEX00157,2019-02-05,NaN,NaN,0.007600,NaN,NaN,839.0,NaN,NaN,...,10.991,2.13180,0.0178,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29911,MEX00157,2020-07-27,NaN,NaN,NaN,NaN,NaN,538.0,NaN,NaN,...,5.502,1.12470,0.0070,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38382,MEX05617,2018-11-18,NaN,NaN,0.005925,NaN,NaN,44000.0,NaN,NaN,...,7.892,1.72434,0.0669,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38391,MEX05620,2018-02-16,NaN,NaN,0.000500,NaN,NaN,55200.0,NaN,NaN,...,2.268,1.00885,0.0070,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38392,MEX05620,2018-04-05,NaN,NaN,0.000500,NaN,NaN,54500.0,NaN,NaN,...,3.144,1.70145,0.0070,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38393,MEX05620,2018-05-06,NaN,NaN,0.000500,NaN,NaN,53900.0,NaN,NaN,...,4.336,1.51027,0.0116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38394,MEX05620,2018-11-14,NaN,NaN,0.000500,NaN,NaN,56400.0,NaN,NaN,...,2.711,1.39466,0.0374,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
FECALCOLI_Data[~FECALCOLI_Data['Station'].str.startswith('MEX')].Station.value_counts()

Station
URY00076    1073
URY00174      93
URY00077      92
URY00078      92
URY00080      92
URY00175      92
URY00079      91
Name: count, dtype: int64

In [62]:
FECALCOLI_Data[FECALCOLI_Data.Station == 'URY00076']

,Station,Date,Time,Alk-Tot,Chl-a,Cl-Tot,DRP,EC,H-T,NH4N,...,TOC,TON,TRP,Ca-Dis,Fe-Dis,Mg-Dis,Na-Dis,Pb-Dis,SO4-Dis,Zn-Dis
39286,URY00076,2018-01-02,NaN,52.0,NaN,NaN,NaN,139.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39287,URY00076,2018-01-03,NaN,52.0,NaN,NaN,NaN,140.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39288,URY00076,2018-01-04,NaN,55.0,NaN,NaN,NaN,141.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39289,URY00076,2018-01-05,NaN,59.0,NaN,NaN,NaN,143.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39290,URY00076,2018-01-08,NaN,58.0,NaN,NaN,NaN,142.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40392,URY00076,2023-05-04,NaN,60.0,NaN,NaN,NaN,191.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40393,URY00076,2023-05-05,NaN,60.0,NaN,NaN,NaN,195.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40394,URY00076,2023-05-08,NaN,59.0,NaN,NaN,NaN,196.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40395,URY00076,2023-05-09,NaN,58.0,NaN,NaN,NaN,199.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40396,URY00076,2023-05-10,NaN,55.0,NaN,NaN,NaN,190.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN