In [20]:
import pandas as pd
import numpy as np

In [21]:
erie1 = pd.read_csv('data/Gemstat_Data_merged_sattelite/Lake_erie/Lake_erie_7_days.csv')
garda1 = pd.read_csv('data/Gemstat_Data_merged_sattelite/Lake_garda/Lake_garda_7_days.csv')
genewa1 = pd.read_csv('data/Gemstat_Data_merged_sattelite/Lake_Geneva/Lake_Geneva_7_days.csv')

In [22]:
erie1.head(1)

,Site_name,Country,Country_code,Latitude,Longitude,Date_Time_UTC,Water_body_type,Water_type,Depth,Chla,...,B11,B12,B2,B3,B4,B5,B6,B7,B8,B8A
0,Lake Erie,United States of America (the),US,41.7622,-83.3312,2020-07-28 15:45:00,1,4,5.62,28.47,...,0.0147,0.0125,0.0501,0.0725,0.0376,0.0433,0.0251,0.0241,0.0221,0.0206

In [23]:
garda1.head(1)

,Unnamed: 0,Site_name,Country,Country_code,Latitude,Longitude,Date_Time_UTC,Water_body_type,Water_type,Depth,...,B11,B12,B2,B3,B4,B5,B6,B7,B8,B8A
0,2605,Garda,Italy,IT,45.4781,10.604,2017-09-21T11:05,1,6.0,NaN,...,0.002,0.0022,0.0432,0.04885,0.00795,0.00435,0.0012,0.0017,0.00215,0.00175

In [24]:
genewa1.head(1)

,Unnamed: 0,Site_name,Country,Country_code,Latitude,Longitude,Date_Time_UTC,Water_body_type,Water_type,Depth,...,B11,B12,B2,B3,B4,B5,B6,B7,B8,B8A
0,1146,Lake Geneva,Switzerland,CH,46.5002,6.6608,2018-10-18T11:17,1,6.0,110.0,...,0.004,0.0038,0.01765,0.0177,0.00845,0.0082,0.0068,0.00635,0.0068,0.00575

In [25]:
erie1.rename(columns={'Chla': 'Chl-a'}, inplace=True)
genewa1.rename(columns={'Chla': 'Chl-a'}, inplace=True)
garda1.rename(columns={'Chla': 'Chl-a'}, inplace=True)

In [26]:
erie1.head(1)

,Site_name,Country,Country_code,Latitude,Longitude,Date_Time_UTC,Water_body_type,Water_type,Depth,Chl-a,...,B11,B12,B2,B3,B4,B5,B6,B7,B8,B8A
0,Lake Erie,United States of America (the),US,41.7622,-83.3312,2020-07-28 15:45:00,1,4,5.62,28.47,...,0.0147,0.0125,0.0501,0.0725,0.0376,0.0433,0.0251,0.0241,0.0221,0.0206

In [27]:
merged_df = pd.concat([erie1, genewa1, garda1], ignore_index=True)
print(merged_df.head())

   Site_name                         Country Country_code  Latitude  \
0  Lake Erie  United States of America (the)           US   41.7622
1  Lake Erie  United States of America (the)           US   41.8274
2  Lake Erie  United States of America (the)           US   41.8339
3  Lake Erie  United States of America (the)           US   41.6585
4  Lake Erie  United States of America (the)           US   41.7614

   Longitude        Date_Time_UTC  Water_body_type  Water_type  Depth  Chl-a  \
0   -83.3312  2020-07-28 15:45:00                1         4.0   5.62  28.47
1   -83.1956  2020-07-28 12:45:00                1         4.0   8.84  16.77
2   -83.3597  2020-07-28 12:07:00                1         4.0   5.53  14.30
3   -83.1463  2020-07-28 13:51:00                1         4.0   6.34   4.64
4   -83.3329  2020-08-10 15:40:00                1         4.0   5.27  20.48

   ...      B3      B4      B5      B6      B7      B8     B8A  Unnamed: 0  \
0  ...  0.0725  0.0376  0.0433  0.0251  0.0241  0.0221  0.0206         NaN
1  ...  0.0714  0.0370  0.0363  0.0228  0.0233  0.0197  0.0182         NaN
2  ...  0.0783  0.0433  0.0444  0.0306  0.0312  0.0272  0.0272         NaN
3  ...  0.0532  0.0253  0.0241  0.0192  0.0211  0.0189  0.0176         NaN
4  ...  0.0713  0.0346  0.0344  0.0178  0.0160  0.0156  0.0130         NaN

   Chla_plus_phaeo  aCDOM440
0              NaN       NaN
1              NaN       NaN
2              NaN       NaN
3              NaN       NaN
4              NaN       NaN

[5 rows x 28 columns]

In [28]:
merged_df

,Site_name,Country,Country_code,Latitude,Longitude,Date_Time_UTC,Water_body_type,Water_type,Depth,Chl-a,...,B3,B4,B5,B6,B7,B8,B8A,Unnamed: 0,Chla_plus_phaeo,aCDOM440
0,Lake Erie,United States of America (the),US,41.7622,-83.3312,2020-07-28 15:45:00,1,4.0,5.62,28.47000,...,0.07250,0.03760,0.04330,0.02510,0.02410,0.02210,0.02060,NaN,NaN,NaN
1,Lake Erie,United States of America (the),US,41.8274,-83.1956,2020-07-28 12:45:00,1,4.0,8.84,16.77000,...,0.07140,0.03700,0.03630,0.02280,0.02330,0.01970,0.01820,NaN,NaN,NaN
2,Lake Erie,United States of America (the),US,41.8339,-83.3597,2020-07-28 12:07:00,1,4.0,5.53,14.30000,...,0.07830,0.04330,0.04440,0.03060,0.03120,0.02720,0.02720,NaN,NaN,NaN
3,Lake Erie,United States of America (the),US,41.6585,-83.1463,2020-07-28 13:51:00,1,4.0,6.34,4.64000,...,0.05320,0.02530,0.02410,0.01920,0.02110,0.01890,0.01760,NaN,NaN,NaN
4,Lake Erie,United States of America (the),US,41.7614,-83.3329,2020-08-10 15:40:00,1,4.0,5.27,20.48000,...,0.07130,0.03460,0.03440,0.01780,0.01600,0.01560,0.01300,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3815,Garda,Italy,IT,45.0900,10.4600,2017-06-07T08:30,1,6.0,NaN,1.00661,...,0.03465,0.02350,0.05375,0.22540,0.31595,0.31955,0.32565,2656.0,NaN,0.033327
3816,Garda,Italy,IT,45.0900,10.4600,2017-06-07T08:30,1,6.0,NaN,1.00661,...,0.03465,0.02350,0.05375,0.22540,0.31595,0.31955,0.32565,2656.0,NaN,0.033327
3817,Garda,Italy,IT,45.0900,10.4600,2017-06-07T08:30,1,6.0,NaN,1.00661,...,0.03465,0.02350,0.05375,0.22540,0.31595,0.31955,0.32565,2656.0,NaN,0.033327
3818,Garda,Italy,IT,45.4915,10.5335,2020-09-10T10:20,1,6.0,NaN,0.27000,...,0.04695,0.01710,0.01650,0.01765,0.01765,0.01370,0.01330,2787.0,NaN,0.057000
3819,Garda,Italy,IT,45.5010,10.5393,2020-09-10T10:35,1,6.0,NaN,4.18000,...,0.03355,0.01685,0.01855,0.02045,0.01965,0.01450,0.01655,2788.0,NaN,0.074000

In [29]:
merged_df.columns

Index(['Site_name', 'Country', 'Country_code', 'Latitude', 'Longitude',
       'Date_Time_UTC', 'Water_body_type', 'Water_type', 'Depth', 'Chl-a',
       'TSS', 'Turbidity', 'Secchi_depth', 'Date', 'Time', 'B11', 'B12', 'B2',
       'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'Unnamed: 0',
       'Chla_plus_phaeo', 'aCDOM440'],
      dtype='object')

In [30]:
new_df = merged_df[['Chl-a', 'B11', 'B12', 'B2',
       'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A',]]

In [31]:
new_df

,Chl-a,B11,B12,B2,B3,B4,B5,B6,B7,B8,B8A
0,28.47000,0.01470,0.01250,0.05010,0.07250,0.03760,0.04330,0.02510,0.02410,0.02210,0.02060
1,16.77000,0.01410,0.01110,0.05110,0.07140,0.03700,0.03630,0.02280,0.02330,0.01970,0.01820
2,14.30000,0.02110,0.01920,0.05890,0.07830,0.04330,0.04440,0.03060,0.03120,0.02720,0.02720
3,4.64000,0.01520,0.01270,0.04730,0.05320,0.02530,0.02410,0.01920,0.02110,0.01890,0.01760
4,20.48000,0.00550,0.00370,0.05360,0.07130,0.03460,0.03440,0.01780,0.01600,0.01560,0.01300
...,...,...,...,...,...,...,...,...,...,...,...
3815,1.00661,0.13390,0.06985,0.01245,0.03465,0.02350,0.05375,0.22540,0.31595,0.31955,0.32565
3816,1.00661,0.13390,0.06985,0.01245,0.03465,0.02350,0.05375,0.22540,0.31595,0.31955,0.32565
3817,1.00661,0.13390,0.06985,0.01245,0.03465,0.02350,0.05375,0.22540,0.31595,0.31955,0.32565
3818,0.27000,0.00535,0.00355,0.04060,0.04695,0.01710,0.01650,0.01765,0.01765,0.01370,0.01330
3819,4.18000,0.00425,0.00380,0.03535,0.03355,0.01685,0.01855,0.02045,0.01965,0.01450,0.01655

In [32]:
new_df.to_csv('data/Final Data/Chl-a-7-day.csv', index=False)

In [33]:
new_df.corr()['Chl-a'].sort_values(ascending=False)

Chl-a    1.000000
B5       0.357805
B3       0.237378
B4       0.219530
B2       0.160257
B6       0.022401
B7       0.003633
B8      -0.017645
B8A     -0.017984
B12     -0.036748
B11     -0.047562
Name: Chl-a, dtype: float64

In [36]:

from statsmodels.graphics.gofplots import qqplot
from statsmodels.stats.stattools import jarque_bera

import matplotlib.pyplot as plt

# Shapiro-Wilk test
stat, p = shapiro(new_df['Chl-a'])
print('Statistics=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
    print('Sample looks Gaussian (fail to reject H0)')
# Check normality without using scipy

# Jarque-Bera test
jb_stat, jb_p, _, _ = jarque_bera(new_df['Chl-a'])
print('Jarque-Bera Statistics=%.3f, p=%.3f' % (jb_stat, jb_p))
if jb_p > 0.05:
    print('Sample looks Gaussian (fail to reject H0)')
else:
    print('Sample does not look Gaussian (reject H0)')
    print('Sample does not look Gaussian (reject H0)')

# Q-Q plot
plt.figure(figsize=(10, 6))
sns.histplot(new_df['Chl-a'], kde=True)
plt.title('Histogram of Chl-a')
plt.show()

plt.figure(figsize=(10, 6))
stats.probplot(new_df['Chl-a'], dist="norm", plot=plt)
plt.title('Q-Q plot of Chl-a')
plt.show()

ModuleNotFoundError: No module named 'statsmodels'

In [37]:
!pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.2 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in /Users/kavyasmac/Desktop/Time Pass/WQI Analysis/untitled folder/WaterQualityAnalysis/venv/lib/python3.11/site-packages (from statsmodels) (2.2.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /Users/kavyasmac/Desktop/Time Pass/WQI Analysis/untitled folder/WaterQualityAnalysis/venv/lib/python3.11/site-packages (from statsmodels) (1.15.2)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /Users/kavyasmac/Desktop/Time Pass/WQI Analysis/untitled folder/WaterQualityAnalysis/venv/lib/python3.11/site-packages (from statsmodels) (2.2.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: packaging>=21.3 in /Users/kavyasmac/Desktop/Time Pass/WQI Analysis/untitled folder/WaterQualityAnalysis/venv/lib/python3.11/site-packages (from statsmodels) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/kavyasmac/Desktop/Time Pass/WQI Analysis/untitled folder/WaterQualityAnalysis/venv/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/kavyasmac/Desktop/Time Pass/WQI Analysis/untitled folder/WaterQualityAnalysis/venv/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/kavyasmac/Desktop/Time Pass/WQI Analysis/untitled folder/WaterQualityAnalysis/venv/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/kavyasmac/Desktop/Time Pass/WQI Analysis/untitled folder/WaterQualityAnalysis/venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.4-cp311-cp311-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 721.2 kB/s eta 0:00:0000:0100:01
Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
Installing collected packages: patsy, statsmodels
Successfully installed patsy-1.0.1 statsmodels-0.14.4